name: Breaking-Blocks
main: com.senpai.breakingblocks.Main
version: 1.0
api-version: 1.13
commands:
   blocks:
      description: Zeigt wer dieses Plugin entwickelt hat
      usage: /blocks
   who:
      description: Zeigt wer dieses Plugin entwickelt hat
      usage: /who
      